(in-package "LIB~")

(defvar *std-package-details*
  '(("STD" "NIL"
     ())
    ("STD.FUN" "Functions section in CL Cookbook"
     (("DEFUN" "CL")
      ("VALUES" "CL")
      ("MULTIPLE-VALUE-BIND" "CL")
      ("LAMBDA" "CL")
      ("FUNCALL" "CL")
      ("APPLY" "CL")
      ("DEFSETF" "CL")
      ("MAPC" "CL")
      ("MAPHASH" "CL")
      ("COMPILED-FUNCTION" "CL")
      ("FUNCTION" "CL")
      ("FUNCTIONP" "CL")
      ("REDUCE" "CL")
      ("MAPCAN" "CL")
      ("MAP" "CL")
      ("MAPLIST" "CL")
      ("MAPCAR" "CL")
      ("MAPL" "CL")
      ("MAPCON" "CL")
      ("MAP-INTO" "CL")
      ("DEFMACRO" "CL")
      ("COMPLEMENT" "CL")
      ("IDENTITY" "CL")
      ("FBOUNDP" "CL")
      ("CONSTANTLY" "CL")
      ))
    ("STD.CONT" "Containers parent package"
     ())
    ("STD.CONT.LIST" "Container's list related items."
     (("LIST*" "CL")
      ("LIST" "CL")
      ("CONS" "CL")
      ("REST" "CL")
      ("BUTLAST" "CL")
      ("NBUTLAST" "CL")
      ("LAST" "CL")
      ("NREVERSE" "CL")
      ("REVERSE" "CL")
      ("REVAPPEND" "CL")
      ("APPEND" "CL")
      ("PUSHNEW" "CL")
      ("PUSH" "CL")
      ("POP" "CL")
      ("NULL" "CL")
      ("LISTP" "CL")
      ("LDIFF" "CL")
      ("TAILP" "CL")
      ("MAKE-LIST" "CL")
      ("NRECONC" "CL")
      ("CONSP" "CL")
      ("SUBST" "CL")
      ("SUBLIS" "CL")
      ("NSUBST-IF" "CL")
      ("SUBSTITUTE" "CL")
      ("SUBSTITUTE-IF" "CL")
      ("SUBST-IF-NOT" "CL")
      ("NSUBSTITUTE-IF-NOT" "CL")
      ("SUBSTITUTE-IF-NOT" "CL")
      ("SUBST-IF" "CL")
      ("NSUBSTITUTE" "CL")
      ("NSUBST-IF-NOT" "CL")
      ("NSUBSTITUTE-IF" "CL")
      ("NSUBST" "CL")
      ("ATOM" "CL")
      ("LIST-LENGTH" "CL")
      ("COPY-TREE" "CL")
      ("TREE-EQUAL" "CL")
      ("CONCATENATE" "CL")
      ("MULTIPLE-VALUE-LIST" "CL")
      ("VALUES-LIST" "CL")
      ("ADJOIN" "CL")
      ("NSET-EXCLUSIVE-OR" "CL")
      ("NCONC" "CL")
      ("NSUBLIS" "CL")
      ("COPY-LIST" "CL")
      ("ENDP" "CL")
      ("MEMBER" "CL")
      ))
    ("STD.CONT.LIST.ACCESS" "List access functions"
     (("CAR" "CL")
      ("CDR" "CL")
      ("CDAR" "CL")
      ("CAAR" "CL")
      ("CAAAR" "CL")
      ("CAAAAR" "CL")
      ("CDAAR" "CL")
      ("CADR" "CL")
      ("CDDR" "CL")
      ("CAADR" "CL")
      ("CADDDR" "CL")
      ("CDADAR" "CL")
      ("CADAR" "CL")
      ("CDADR" "CL")
      ("CDAADR" "CL")
      ("CDDAR" "CL")
      ("CDAAAR" "CL")
      ("CAADDR" "CL")
      ("CDDDAR" "CL")
      ("CADDAR" "CL")
      ("CDADDR" "CL")
      ("CADADR" "CL")
      ("CADAAR" "CL")
      ("CDDDDR" "CL")
      ("CAADAR" "CL")
      ("CDDAAR" "CL")
      ("CDDADR" "CL")
      ("CADDR" "CL")
      ("CDDDR" "CL")
      ("CAAADR" "CL")
      ("NTHCDR" "CL")
      ("FIRST" "CL")
      ("SECOND" "CL")
      ("THIRD" "CL")
      ("FOURTH" "CL")
      ("FIFTH" "CL")
      ("SIXTH" "CL")
      ("SEVENTH" "CL")
      ("EIGHTH" "CL")
      ("NINTH" "CL")
      ("TENTH" "CL")
      ("NTH" "CL")
      ))
    ("STD.CONT.ITER" "Container iteration"
     ())
    ("STD.CONT.ARRAY" "Container array"
     (("ARRAY-TOTAL-SIZE-LIMIT" "CL")
      ("MAKE-ARRAY" "CL")
      ("SIMPLE-ARRAY" "CL")
      ("ADJUST-ARRAY" "CL")
      ("ARRAY-ROW-MAJOR-INDEX" "CL")
      ("ROW-MAJOR-AREF" "CL")
      ("AREF" "CL")
      ("ARRAY-DIMENSION" "CL")
      ("ARRAY-DIMENSIONS" "CL")
      ("ARRAY-HAS-FILL-POINTER-P" "CL")
      ("UPGRADED-ARRAY-ELEMENT-TYPE" "CL")
      ("ARRAY-TOTAL-SIZE" "CL")
      ("ARRAY-RANK" "CL")
      ("VECTOR-PUSH" "CL")
      ("VECTOR" "CL")
      ("VECTORP" "CL")
      ("SIMPLE-BIT-VECTOR-P" "CL")
      ("VECTOR-PUSH-EXTEND" "CL")
      ("VECTOR-POP" "CL")
      ("SIMPLE-VECTOR-P" "CL")
      ("FILL-POINTER" "CL")
      ("CONCATENATE" "CL")
      ("ARRAYP" "CL")
      ("SIMPLE-VECTOR" "CL")
      ("ADJUSTABLE-ARRAY-P" "CL")
      ("ARRAY-RANK-LIMIT" "CL")
      ("ARRAY-IN-BOUNDS-P" "CL")
      ("ARRAY-DIMENSION-LIMIT" "CL")
      ("ARRAY-DISPLACEMENT" "CL")
      ("SVREF" "CL")
      ("BIT" "CL")
      ("SBIT" "CL")
      ))
    ("STD.CONT.HASH" "Container hash"
     (("MAKE-HASH-TABLE" "CL")
      ("GETHASH" "CL")
      ("REMHASH" "CL")
      ("MAPHASH" "CL")
      ("WITH-HASH-TABLE-ITERATOR" "CL")
      ("HASH-TABLE-COUNT" "CL")
      ("HASH-TABLE" "CL")
      ("HASH-TABLE-REHASH-THRESHOLD" "CL")
      ("HASH-TABLE-P" "CL")
      ("HASH-TABLE-TEST" "CL")
      ("HASH-TABLE-WEAKNESS" "CL")
      ("DEFINE-HASH-TABLE-TEST" "CL")
      ("WITH-LOCKED-HASH-TABLE" "CL")
      ("HASH-TABLE-SYNCHRONIZED-P" "CL")
      ("HASH-TABLE-SIZE" "CL")
      ("HASH-TABLE-REHASH-SIZE" "CL")
      ("CLRHASH" "CL")
      ("SXHASH" "CL")
      ))
    ("STD.CONT.ALIST" "Container alist"
     (("ASSOC-IF" "CL")
      ("ASSOC-IF-NOT" "CL")
      ("RASSOC" "CL")
      ("RASSOC-IF" "CL")
      ("ASSOC" "CL")
      ("RASSOC-IF-NOT" "CL")
      ("COPY-ALIST" "CL")
      ))
    ("STD.CONT.PLIST" "Container plist"
     (("PAIRLIS" "CL")
      ("GETF" "CL")
      ("REMPROP" "CL")
      ("PSETF" "CL")
      ("REMF" "CL")
      ("SYMBOL-PLIST" "CL")
      ("GET-PROPERTIES" "CL")
      ("PSETQ" "CL")
      ("GET" "CL")
      ))
    ("STD.CONT.SEQUENCE" "Container sequence"
     (("LENGTH" "CL")
      ("COUNT" "CL")
      ("POSITION" "CL")
      ("POSITION-IF-NOT" "CL")
      ("POSITION-IF" "CL")
      ("SEARCH" "CL")
      ("STABLE-SORT" "CL")
      ("SORT" "CL")
      ("MERGE" "CL")
      ("REPLACE" "CL")
      ("REMOVE" "CL")
      ("DELETE-IF-NOT" "CL")
      ("DELETE-IF" "CL")
      ("REMOVE-IF" "CL")
      ("REMOVE-DUPLICATES" "CL")
      ("REMOVE-IF-NOT" "CL")
      ("DELETE" "CL")
      ("DELETE-DUPLICATES" "CL")
      ("ELT" "CL")
      ("FIND-IF-NOT" "CL")
      ("FIND-IF" "CL")
      ("FIND" "CL")
      ("NOTEVERY" "CL")
      ("EVERY" "CL")
      ("SOME" "CL")
      ("NOTANY" "CL")
      ("MAKE-SEQUENCE" "CL")
      ("CONCATENATE" "CL")
      ("SUBSEQ" "CL")
      ("MEMBER-IF-NOT" "CL")
      ("MEMBER-IF" "CL")
      ("MISMATCH" "CL")
      ("COPY-SEQ" "CL")
      ("COUNT-IF" "CL")
      ("COUNT-IF-NOT" "CL")
      ("FILL" "CL")
      ))
    ("STD.CONT.SETS" "Container sets"
     (("NINTERSECTION" "CL")
      ("INTERSECTION" "CL")
      ("NSET-DIFFERENCE" "CL")
      ("SET-DIFFERENCE" "CL")
      ("UNION" "CL")
      ("NUNION" "CL")
      ("SET-EXCLUSIVE-OR" "CL")
      ("SUBSETP" "CL")
      ))
    ("STD.PATTERNS" "Pattern mapping and matching"
     (("DESTRUCTURING-BIND" "CL")
      ))
    ("STD.STR" "String manipulation"
     (("PARSE-INTEGER" "CL")
      ("FORMAT" "CL")
      ("PPRINT-LINEAR" "CL")
      ("PRINT-UNREADABLE-OBJECT" "CL")
      ("PPRINT-TAB" "CL")
      ("PRINT" "CL")
      ("WITH-OUTPUT-TO-STRING" "CL")
      ("STRING-RIGHT-TRIM" "CL")
      ("MAKE-STRING" "CL")
      ("PRIN1-TO-STRING" "CL")
      ("PRINC-TO-STRING" "CL")
      ("CHAR" "CL")
      ("SCHAR" "CL")
      ("CONCATENATE" "CL")
      ("STRING-TRIM" "CL")
      ("STRING-CAPITALIZE" "CL")
      ("STRING-UPCASE" "CL")
      ("STRING-LEFT-TRIM" "CL")
      ("STRING-DOWNCASE" "CL")
      ("STRING-TO-OCTETS" "CL")
      ("WRITE-TO-STRING" "CL")
      ("BOTH-CASE-P" "CL")
      ("MAKE-STRING-INPUT-STREAM" "CL")
      ("NSTRING-UPCASE" "CL")
      ("SIMPLE-STRING-P" "CL")
      ("UPPER-CASE-P" "CL")
      ("NSTRING-CAPITALIZE" "CL")
      ("NSTRING-DOWNCASE" "CL")
      ("LOWER-CASE-P" "CL")
      ))
    ("STD.STR.COMP" "String comparison"
     (("STRING<" "CL")
      ("STRING-NOT-EQUAL" "CL")
      ("STRING<=" "CL")
      ("STRINGP" "CL")
      ("STRING=" "CL")
      ("STRING>" "CL")
      ("STRING/=" "CL")
      ("STRING>=" "CL")
      ("STRING-LESSP" "CL")
      ("STRING-NOT-LESSP" "CL")
      ("STRING-GREATERP" "CL")
      ("STRING-EQUAL" "CL")
      ("STRING-NOT-GREATERP" "CL")
      ))
    ("STD.CHAR" "Character manipulation"
     (("CHAR-UPCASE" "CL")
      ("CHAR-DOWNCASE" "CL")
      ("ALPHA-CHAR-P" "CL")
      ("ALPHANUMERICP" "CL")
      ("CHAR-INT" "CL")
      ("DIGIT-CHAR" "CL")
      ("CHAR-CODE-LIMIT" "CL")
      ("CHARACTERP" "CL")
      ("CODE-CHAR" "CL")
      ("GRAPHIC-CHAR-P" "CL")
      ))
    ("STD.CHAR.COMP" "Character comparison"
     (("CHAR>=" "CL")
      ("CHAR>" "CL")
      ("CHAR=" "CL")
      ("CHAR<=" "CL")
      ("CHAR<" "CL")
      ("CHAR/=" "CL")
      ("CHAR-NOT-LESSP" "CL")
      ("CHAR-NOT-EQUAL" "CL")
      ("CHAR-EQUAL" "CL")
      ("CHAR-LESSP" "CL")
      ("CHAR-NOT-GREATERP" "CL")
      ("CHAR-GREATERP" "CL")
      ))
    ("STD.PKG" "Package management"
     (("PACKAGE" "CL")
      ("DEFPACKAGE" "CL")
      ("FIND-PACKAGE" "CL")
      ("IMPORT" "CL")
      ("REQUIRE" "CL")
      ("*MODULES*" "CL")
      ("*PACKAGE*" "CL")
      ("PACKAGE-NAME" "CL")
      ("PACKAGEP" "CL")
      ("PROVIDE" "CL")
      ("UNEXPORT" "CL")
      ("UNUSE-PACKAGE" "CL")
      ("USE-PACKAGE" "CL")
      ("PACKAGE-USED-BY-LIST" "CL")
      ("DELETE-PACKAGE" "CL")
      ("PACKAGE-NICKNAMES" "CL")
      ("RENAME-PACKAGE" "CL")
      ("KEYWORD" "CL")
      ("IN-PACKAGE" "CL")
      ("PACKAGE-USE-LIST" "CL")
      ("MAKE-PACKAGE" "CL")
      ("SHADOWING-IMPORT" "CL")
      ("SHADOW" "CL")
      ("LIST-ALL-PACKAGES" "CL")
      ("WITH-PACKAGE-ITERATOR" "CL")
      ("EXPORT" "CL")
      ))
    ("STD.PKG.SYMS" "Package symbol management"
     (("DO-ALL-SYMBOLS" "CL")
      ("DO-SYMBOLS" "CL")
      ("DO-EXTERNAL-SYMBOLS" "CL")
      ("PACKAGE-SHADOWING-SYMBOLS" "CL")
      ("FIND-ALL-SYMBOLS" "CL")
      ("SYMBOL-PACKAGE" "CL")
      ("MAKE-SYMBOL" "CL")
      ("SYMBOL-VALUE" "CL")
      ("SYMBOL-NAME" "CL")
      ("COPY-SYMBOL" "CL")
      ("FIND-SYMBOL" "CL")
      ("SYMBOL" "CL")
      ("SYMBOLP" "CL")
      ("SYMBOL-FUNCTION" "CL")
      ("UNINTERN" "CL")
      ("INTERN" "CL")
      ("MAKUNBOUND" "CL")
      ("FBOUNDP" "CL")
      ("BOUNDP" "CL")
      ("FMAKUNBOUND" "CL")
      ))
    ("STD.LANG" "Language lib"
     (
      ))
    ("STD.LANG.COMPILE" "Language/compilation"
     (("COMPILATION-SPEED" "CL")
      ("SPEED" "CL")
      ("OPTIMIZE" "CL")
      ("NOTINLINE" "CL")
      ("WITH-COMPILATION-UNIT" "CL")
      ("*COMPILE-VERBOSE*" "CL")
      ("DECLAIM" "CL")
      ("PROCLAIM" "CL")
      ("LOCALLY" "CL")
      ("INLINE" "CL")
      ("SAFETY" "CL")
      ("DECLARE" "CL")
      ("SPECIAL" "CL")
      ("DYNAMIC-EXTENT" "CL")
      ("IGNORABLE" "CL")
      ("IGNORE" "CL")
      ))
    ("STD.LANG.BLOCKS" "Code blocks"
     (("WHILE" "CL")
      ("LOOP" "CL")
      ("GO" "CL")
      ("BLOCK" "CL")
      ("RETURN-FROM" "CL")
      ("TAGBODY" "CL")
      ("RETURN" "CL")
      ("LOOP-FINISH" "CL")
      ("PROGN" "CL")
      ("NTH-VALUE" "CL")
      ("DO" "CL")
      ("DOTIMES" "CL")
      ("DOLIST" "CL")
      ("PROGV" "CL")
      ("PROG1" "CL")
      ("PROG*" "CL")
      ("PROG" "CL")
      ("MULTIPLE-VALUE-PROG1" "CL")
      ("PROG2" "CL")
      ("DO*" "CL")
      ))
    ("STD.LANG.DEFN" "Definitions"
     (("LET" "CL")
      ("LET*" "CL")
      ("FLET" "CL")
      ("LABELS" "CL")
      ("MACROLET" "CL")
      ("DEFINE-SYMBOL-MACRO" "CL")
      ("DEFVAR" "CL")
      ("DEFTYPE" "CL")
      ("DEFPARAMETER" "CL")
      ("DEFCONSTANT" "CL")
      ("DEFINE-SETF-EXPANDER" "CL")
      ("DEFINE-MODIFY-MACRO" "CL")
      ("DEFINE-COMPILER-MACRO" "CL")
      ))
    ("STD.LANG.BASE" "Language basic constructs"
     (("EQUAL" "CL")
      ("COND" "CL")
      ("SET" "CL")
      ("OR" "CL")
      ("WHEN" "CL")
      ("EQ" "CL")
      ("AND" "CL")
      ("NOT" "CL")
      ("T" "CL")
      ("NIL" "CL")
      ("EVAL" "CL")
      ("CASE" "CL")
      ("QUOTE" "CL")
      ("IF" "CL")
      ("SETQ" "CL")
      ("MULTIPLE-VALUE-SETQ" "CL")
      ("MULTIPLE-VALUE-CALL" "CL")
      ("SETF" "CL")
      ("UNWIND-PROTECT" "CL")
      ("MULTIPLE-VALUE-LIST" "CL")
      ("VALUES-LIST" "CL")
      ("VALUES" "CL")
      ("THE" "CL")
      ("LOAD-TIME-VALUE" "CL")
      ("EVAL-WHEN" "CL")
      ("SET-SYNTAX-FROM-CHAR" "CL")
      ("SPECIAL-OPERATOR-P" "CL")
      ("LAMBDA-PARAMETERS-LIMIT" "CL")
      ("*READ-BASE*" "CL")
      ("KEYWORD" "CL")
      ("GENTEMP" "CL")
      ("KEYWORDP" "CL")
      ("&OPTIONAL" "CL")
      ("&ENVIRONMENT" "CL")
      ("&REST" "CL")
      ("&KEY" "CL")
      ("&WHOLE" "CL")
      ("&AUX" "CL")
      ("LAMBDA-LIST-KEYWORDS" "CL")
      ("OTHERWISE" "CL")
      ("ETYPECASE" "CL")
      ("DECLARATION" "CL")
      ("SATISFIES" "CL")
      ("UNLESS" "CL")
      ("COMPILED-FUNCTION-P" "CL")
      ("ECASE" "CL")
      ("EQUALP" "CL")
      ("EQL" "CL")
      ("RPLACA" "CL")
      ("RPLACD" "CL")
      ("GET-SETF-EXPANSION" "CL")
      ("CHECK-TYPE" "CL")
      ("TYPECASE" "CL")
      ("FDEFINITION" "CL")
      ("SET-MACRO-CHARACTER" "CL")
      ("CONSTANTP" "CL")
      ("MULTIPLE-VALUES-LIMIT" "CL")
      ("CALL-ARGUMENTS-LIMIT" "CL")
      ))
    ("STD.LANG.MACRO" "Macro functions"
     (("COMPILER-MACRO-FUNCTION" "CL")
      ("COMPILER-MACRO" "CL")
      ("&BODY" "CL")
      ("MAKE-DISPATCH-MACRO-CHARACTER" "CL")
      ("MACROEXPAND" "CL")
      ("MACROEXPAND-1" "CL")
      ("MACRO-FUNCTION" "CL")
      ("SYMBOL-MACROLET" "CL")
      ("*GENSYM-COUNTER*" "CL")
      ("GENSYM" "CL")
      ))
    ("STD.DATETIME" "Datetime"
     (("GET-UNIVERSAL-TIME" "CL")
      ("DECODE-UNIVERSAL-TIME" "CL")
      ("GET-DECODED-TIME" "CL")
      ("ENCODE-UNIVERSAL-TIME" "CL")
      ("INTERNAL-TIME-UNITS-PER-SECOND" "CL")
      ("SLEEP" "CL")
      ("GET-INTERNAL-REAL-TIME" "CL")
      ("GET-INTERNAL-RUN-TIME" "CL")
      ("TIME" "CL")
      ))
    ("STD.REPL" "Repl and development helpers"
     (("+" "CL")
      ("++" "CL")
      ("+++" "CL")
      ("APROPOS" "CL")
      ("LOAD" "CL")
      ("MAKE-LOAD-FORM" "CL")
      ("*PRINT-LEVEL*" "CL")
      ("VARIABLE" "CL")
      ("APROPOS-LIST" "CL")
      ("READTABLE" "CL")
      ("*PRINT-PPRINT-DISPATCH*" "CL")
      ("*READ-EVAL*" "CL")
      ("UNTRACE" "CL")
      ("*MACROEXPAND-HOOK*" "CL")
      ("INSPECT" "CL")
      ("DESCRIBE" "CL")
      ("DRIBBLE" "CL")
      ("LISP-IMPLEMENTATION-TYPE" "CL")
      ("LISP-IMPLEMENTATION-VERSION" "CL")
      ("*" "CL")
      ("**" "CL")
      ("***" "CL")
      ("*LOAD-TRUENAME*" "CL")
      ("*READ-BASE*" "CL")
      ("*PRINT-ESCAPE*" "CL")
      ("COPY-PPRINT-DISPATCH" "CL")
      ("GET-MACRO-CHARACTER" "CL")
      ("SHORT-SITE-NAME" "CL")
      ("*COMPILE-FILE-PATHNAME*" "CL")
      ("MACHINE-VERSION" "CL")
      ("DESCRIBE-OBJECT" "CL")
      ("FUNCTION-LAMBDA-EXPRESSION" "CL")
      ("READTABLE-CASE" "CL")
      ("*READTABLE*" "CL")
      ("SET-PPRINT-DISPATCH" "CL")
      ("*PRINT-CIRCLE*" "CL")
      ("*PRINT-RADIX*" "CL")
      ("CLEAR-OUTPUT" "CL")
      ("ROOM" "CL")
      ("*TRACE-OUTPUT*" "CL")
      ("*PRINT-LINES*" "CL")
      ("SOFTWARE-TYPE" "CL")
      ("MACHINE-TYPE" "CL")
      ("/" "CL")
      ("//" "CL")
      ("///" "CL")
      ("DISASSEMBLE" "CL")
      ("*PRINT-CASE*" "CL")
      ("PPRINT-POP" "CL")
      ("PPRINT-EXIT-IF-LIST-EXHAUSTED" "CL")
      ("*PRINT-LENGTH*" "CL")
      ("READTABLEP" "CL")
      ("*PRINT-MISER-WIDTH*" "CL")
      ("*LOAD-PRINT*" "CL")
      ("MACHINE-INSTANCE" "CL")
      ("LONG-SITE-NAME" "CL")
      ("*TERMINAL-IO*" "CL")
      ("*COMPILE-FILE-TRUENAME*" "CL")
      ("COMPILE-FILE-PATHNAME" "CL")
      ("TRANSLATE-LOGICAL-PATHNAME" "CL")
      ("*READ-DEFAULT-FLOAT-FORMAT*" "CL")
      ("*PRINT-READABLY*" "CL")
      ("*COMPILE-PRINT*" "CL")
      ("STEP" "CL")
      ("TRACE" "CL")
      ("*PRINT-ARRAY*" "CL")
      ("*READ-SUPPRESS*" "CL")
      ("GET-DISPATCH-MACRO-CHARACTER" "CL")
      ("SOFTWARE-VERSION" "CL")
      ("*FEATURES*" "CL")
      ("*DEBUG-IO*" "CL")
      ("TRANSLATE-PATHNAME" "CL")
      ("PPRINT-TABULAR" "CL")
      ("SET-DISPATCH-MACRO-CHARACTER" "CL")
      ("PPRINT-LOGICAL-BLOCK" "CL")
      ("COMPILE-FILE" "CL")
      ("*LOAD-VERBOSE*" "CL")
      ("COPY-READTABLE" "CL")
      ("FORMATTER" "CL")
      ("BREAK" "CL")
      ("ED" "CL")
      ("DEBUG" "CL")
      ("DOCUMENTATION" "CL")
      ("COMPILE" "CL")
      ("INVOKE-DEBUGGER" "CL")
      ("TIME" "CL")
      ))
    ("STD.IO" "Input output IO functions"
     (("*STANDARD-OUTPUT*" "CL")
      ("*STANDARD-INPUT*" "CL")
      ("*ERROR-OUTPUT*" "CL")
      ("WRITE-LINE" "CL")
      ("Y-OR-N-P" "CL")
      ("YES-OR-NO-P" "CL")
      ("WRITE-TO-STRING" "CL")
      ("TERPRI" "CL")
      ("READ-LINE" "CL")
      ("FRESH-LINE" "CL")
      ("WRITE-STRING" "CL")
      ("*QUERY-IO*" "CL")
      ("FILE-STRING-LENGTH" "CL")
      ("WITH-OPEN-FILE" "CL")
      ("PRINT-OBJECT" "CL")
      ("PRINT-NOT-READABLE" "CL")
      ("PRINT-NOT-READABLE-OBJECT" "CL")
      ("PPRINT-INDENT" "CL")
      ("UNREAD-CHAR" "CL")
      ("READ-CHAR-NO-HANG" "CL")
      ("READ-BYTE" "CL")
      ("READ-CHAR" "CL")
      ("READ-SEQUENCE" "CL")
      ("READ-FROM-STRING" "CL")
      ("READ-PRESERVING-WHITESPACE" "CL")
      ("READ-DELIMITED-LIST" "CL")
      ("FORCE-OUTPUT" "CL")
      ("FINISH-OUTPUT" "CL")
      ("WRITE-SEQUENCE" "CL")
      ("LISTEN" "CL")
      ("WRITE-BYTE" "CL")
      ("PPRINT-FILL" "CL")
      ("*PRINT-GENSYM*" "CL")
      ("*PRINT-RIGHT-MARGIN*" "CL")
      ("PPRINT-DISPATCH" "CL")
      ("*PRINT-BASE*" "CL")
      ("*PRINT-PRETTY*" "CL")
      ("CLEAR-INPUT" "CL")
      ("WITH-STANDARD-IO-SYNTAX" "CL")
      ("PPRINT-NEWLINE" "CL")
      ("CLOSE" "CL")
      ("WITH-INPUT-FROM-STRING" "CL")
      ("WRITE-CHAR" "CL")
      ("WRITE" "CL")
      ("OPEN" "CL")
      ("READ" "CL")
      ("PRINC" "CL")
      ("PRIN1" "CL")
      ("PPRINT" "CL")
      ))
    ("STD.STREAMS" "Streams"
     (("BROADCAST-STREAM" "CL")
      ("MAKE-TWO-WAY-STREAM" "CL")
      ("STRING-STREAM" "CL")
      ("OUTPUT-STREAM-P" "CL")
      ("STREAMP" "CL")
      ("TWO-WAY-STREAM" "CL")
      ("MAKE-BROADCAST-STREAM" "CL")
      ("WITH-OPEN-STREAM" "CL")
      ("GET-OUTPUT-STREAM-STRING" "CL")
      ("STREAM-ELEMENT-TYPE" "CL")
      ("ECHO-STREAM" "CL")
      ("TWO-WAY-STREAM-OUTPUT-STREAM" "CL")
      ("CONCATENATED-STREAM-STREAMS" "CL")
      ("SYNONYM-STREAM" "CL")
      ("MAKE-SYNONYM-STREAM" "CL")
      ("MAKE-STRING-INPUT-STREAM" "CL")
      ("ECHO-STREAM-OUTPUT-STREAM" "CL")
      ("MAKE-ECHO-STREAM" "CL")
      ("TWO-WAY-STREAM-INPUT-STREAM" "CL")
      ("CONCATENATED-STREAM" "CL")
      ("MAKE-STRING-OUTPUT-STREAM" "CL")
      ("OPEN-STREAM-P" "CL")
      ("BROADCAST-STREAM-STREAMS" "CL")
      ("STREAM-ERROR-STREAM" "CL")
      ("MAKE-CONCATENATED-STREAM" "CL")
      ("INTERACTIVE-STREAM-P" "CL")
      ("FILE-STREAM" "CL")
      ("ECHO-STREAM-INPUT-STREAM" "CL")
      ("STREAM-ERROR" "CL")
      ("INPUT-STREAM-P" "CL")
      ("STREAM-EXTERNAL-FORMAT" "CL")
      ("SYNONYM-STREAM-SYMBOL" "CL")
      ("STREAM" "CL")
      ("CHAR-NAME" "CL")
      ("CHAR-CODE" "CL")
      ("NAME-CHAR" "CL")
      ("CHAR-CODE-LIMIT" "CL")
      ("CODE-CHAR" "CL")
      ("PEEK-CHAR" "CL")
      ("*STANDARD-INPUT*" "CL")
      ("*ERROR-OUTPUT*" "CL")
      ("*STANDARD-OUTPUT*" "CL")
      ))
    ("STD.OS" "Operating system OS"
     (
      ))
    ("STD.OS.PATH" "OS path functions"
     (("PATHNAME" "CL")
      ("DIRECTORY" "CL")
      ("DELETE-FILE" "CL")
      ("LOGICAL-PATHNAME-TRANSLATIONS" "CL")
      ("FILE-NAMESTRING" "CL")
      ("PATHNAME-MATCH-P" "CL")
      ("FILE-POSITION" "CL")
      ("PROBE-FILE" "CL")
      ("ENSURE-DIRECTORIES-EXIST" "CL")
      ("MERGE-PATHNAMES" "CL")
      ("FILE-LENGTH" "CL")
      ("WITH-OPEN-FILE" "CL")
      ("PATHNAMEP" "CL")
      ("PATHNAME-HOST" "CL")
      ("PATHNAME-DIRECTORY" "CL")
      ("*LOAD-PATHNAME*" "CL")
      ("PATHNAME-DEVICE" "CL")
      ("*DEFAULT-PATHNAME-DEFAULTS*" "CL")
      ("PATHNAME-VERSION" "CL")
      ("PATHNAME-TYPE" "CL")
      ("DIRECTORY-NAMESTRING" "CL")
      ("NAMESTRING" "CL")
      ("HOST-NAMESTRING" "CL")
      ("ENOUGH-NAMESTRING" "CL")
      ("FILE-NAMESTRING" "CL")
      ("PARSE-NAMESTRING" "CL")
      ("WILD-PATHNAME-P" "CL")
      ("PATHNAME-NAME" "CL")
      ("USER-HOMEDIR-PATHNAME" "CL")
      ("LOAD-LOGICAL-PATHNAME-TRANSLATIONS" "CL")
      ("FILE-AUTHOR" "CL")
      ("RENAME-FILE" "CL")
      ("FILE-WRITE-DATE" "CL")
      ("TRUENAME" "CL")
      ("ENOUGH-NAMESTRING" "CL")
      ("HOST-NAMESTRING" "CL")
      ("MAKE-PATHNAME" "CL")
      ("LOGICAL-PATHNAME" "CL")
      ))
    ("STD.MATH.NUM.LIMITS" "Mathematics numeric limits"
     (("SHORT-FLOAT-EPSILON" "CL")
      ("SINGLE-FLOAT-NEGATIVE-EPSILON" "CL")
      ("SINGLE-FLOAT-EPSILON" "CL")
      ("LONG-FLOAT-NEGATIVE-EPSILON" "CL")
      ("SHORT-FLOAT-NEGATIVE-EPSILON" "CL")
      ("DOUBLE-FLOAT-NEGATIVE-EPSILON" "CL")
      ("LONG-FLOAT-EPSILON" "CL")
      ("DOUBLE-FLOAT-EPSILON" "CL")
      ("LEAST-NEGATIVE-LONG-FLOAT" "CL")
      ("MOST-POSITIVE-DOUBLE-FLOAT" "CL")
      ("DOUBLE-FLOAT-POSITIVE-INFINITY" "CL")
      ("LEAST-NEGATIVE-NORMALIZED-SHORT-FLOAT" "CL")
      ("LEAST-POSITIVE-NORMALIZED-SHORT-FLOAT" "CL")
      ("LEAST-POSITIVE-SINGLE-FLOAT" "CL")
      ("LEAST-POSITIVE-SHORT-FLOAT" "CL")
      ("LEAST-POSITIVE-DOUBLE-FLOAT" "CL")
      ("LEAST-NEGATIVE-NORMALIZED-SINGLE-FLOAT" "CL")
      ("LEAST-NEGATIVE-NORMALIZED-LONG-FLOAT" "CL")
      ("LEAST-NEGATIVE-NORMALIZED-DOUBLE-FLOAT" "CL")
      ("LEAST-POSITIVE-NORMALIZED-DOUBLE-FLOAT" "CL")
      ("LEAST-NEGATIVE-DOUBLE-FLOAT" "CL")
      ("LEAST-NEGATIVE-SHORT-FLOAT" "CL")
      ("LEAST-POSITIVE-NORMALIZED-LONG-FLOAT" "CL")
      ("LEAST-POSITIVE-NORMALIZED-SINGLE-FLOAT" "CL")
      ("LEAST-POSITIVE-LONG-FLOAT" "CL")
      ("MOST-NEGATIVE-FIXNUM" "CL")
      ("MOST-POSITIVE-SHORT-FLOAT" "CL")
      ("MOST-NEGATIVE-DOUBLE-FLOAT" "CL")
      ("MOST-NEGATIVE-LONG-FLOAT" "CL")
      ("MOST-POSITIVE-LONG-FLOAT" "CL")
      ("MOST-NEGATIVE-SINGLE-FLOAT" "CL")
      ("MOST-NEGATIVE-SHORT-FLOAT" "CL")
      ("MOST-POSITIVE-FIXNUM" "CL")
      ("LEAST-NEGATIVE-SINGLE-FLOAT" "CL")
      ("MOST-POSITIVE-SINGLE-FLOAT" "CL")
      ))
    ("STD.MATH.NUM.TYPES" "Mathematics numeric types"
     (("SHORT-FLOAT" "CL")
      ("UPGRADED-COMPLEX-PART-TYPE" "CL")
      ("COMPLEXP" "CL")
      ("DOUBLE-FLOAT" "CL")
      ("LONG" "CL")
      ("FLOAT" "CL")
      ("SINGLE-FLOAT" "CL")
      ("SIGNED" "CL")
      ("UNSIGNED-LONG" "CL")
      ("UNSIGNED-SHORT" "CL")
      ("SIGNED-BYTE" "CL")
      ("INTEGERP" "CL")
      ("NUMBERP" "CL")
      ("INTEGER" "CL")
      ("REAL" "CL")
      ("RATIONAL" "CL")
      ("REALP" "CL")
      ("BIGNUM" "CL")
      ("SIGNUM" "CL")
      ("RATIONALP" "CL")
      ("COMPLEX" "CL")
      ("MINUSP" "CL")
      ("EVENP" "CL")
      ("FIXNUM" "CL")
      ))
    ("STD.MATH.NUM" "Mathematics numeric"
     (("RATIONALIZE" "CL")
      ("INCF" "CL")
      ("INTEGER-LENGTH" "CL")
      ("FLOAT-DIGITS" "CL")
      ("ZEROP" "CL")
      ("MASK-FIELD" "CL")
      ("FLOATING-POINT-OVERFLOW" "CL")
      ("SHIFTF" "CL")
      ("ASH" "CL")
      ("1+" "CL")
      ("DECODE-FLOAT" "CL")
      ("INTEGER-DECODE-FLOAT" "CL")
      ("REALPART" "CL")
      ("IMAGPART" "CL")
      ("FLOATP" "CL")
      ("FTRUNCATE" "CL")
      ("TRUNCATE" "CL")
      ("=" "CL")
      ("<" "CL")
      (">" "CL")
      (">=" "CL")
      ("<=" "CL")
      ("/=" "CL")
      ("RANDOM" "CL")
      ("MAKE-RANDOM-STATE" "CL")
      ("*RANDOM-STATE*" "CL")
      ("RANDOM-STATE-P" "CL")
      ("RANDOM-STATE" "CL")
      ("ROTATEF" "CL")
      ("FLOATING-POINT-INEXACT" "CL")
      ("FLOATING-POINT-INVALID-OPERATION" "CL")
      ("DEPOSIT-FIELD" "CL")
      ("DECF" "CL")
      ("PHASE" "CL")
      ("FLOAT-PRECISION" "CL")
      ("DIGIT-CHAR-P" "CL")
      ("FLOAT-SIGN" "CL")
      ("NUMERATOR" "CL")
      ("ODDP" "CL")
      ("PLUSP" "CL")
      ("FLOAT-RADIX" "CL")
      ("SCALE-FLOAT" "CL")
      ))
    ("STD.MATH.NUM.BITS" "Bitwise arithmetic"
     (("BYTE-POSITION" "CL")
      ("BYTE-SIZE" "CL")
      ("DPB" "CL")
      ("LDB-TEST" "CL")
      ("LDB" "CL")
      ("DPB" "CL")
      )) 
    ("STD.MATH.LOGICAL" "Mathematic logical arithmetic"
     (("BOOLE" "CL")
      ("BOOLE-1" "CL")
      ("BOOLE-IOR" "CL")
      ("BOOLE-ORC2" "CL")
      ("BOOLE-CLR" "CL")
      ("BOOLE-NOR" "CL")
      ("BOOLE-ORC1" "CL")
      ("BOOLE-NAND" "CL")
      ("BOOLE-SET" "CL")
      ("BOOLE-ANDC1" "CL")
      ("BOOLE-ANDC2" "CL")
      ("BOOLE-2" "CL")
      ("BOOLE-AND" "CL")
      ("BOOLE-XOR" "CL")
      ("BOOLE-EQV" "CL")
      ("BOOLE-C2" "CL")
      ("BOOLE-C1" "CL")
      ("BIT-AND" "CL")
      ("BIT-XOR" "CL")
      ("BIT-EQV" "CL")
      ("BIT-ORC2" "CL")
      ("BIT-ORC1" "CL")
      ("BIT-ANDC2" "CL")
      ("BIT-IOR" "CL")
      ("BIT-ANDC1" "CL")
      ("BIT-NOR" "CL")
      ("BIT-NAND" "CL")
      ("BIT-NOT" "CL")
      ("LOGCOUNT" "CL")
      ("LOGORC1" "CL")
      ("LOGTEST" "CL")
      ("LOGORC2" "CL")
      ("LOGANDC1" "CL")
      ("LOGNOT" "CL")
      ("LOGXOR" "CL")
      ("LOGNOR" "CL")
      ("LOGANDC2" "CL")
      ("LOGNAND" "CL")
      ("LOGIOR" "CL")
      ("LOGBITP" "CL")
      ("LOGEQV" "CL")
      ("LOGAND" "CL")
      ))
    ("STD.MATH" "Math STD."
     (
      ))
    ("STD.MATH.FUNCTIONS" "Math functions"
     (("SQRT" "CL")
      ("CONJUGATE" "CL")
      ("SIN" "CL")
      ("GCD" "CL")
      ("TANH" "CL")
      ("ATAN" "CL")
      ("CEILING" "CL")
      ("FLOOR" "CL")
      ("ATANH" "CL")
      ("ASIN" "CL")
      ("LCM" "CL")
      ("SINH" "CL")
      ("FROUND" "CL")
      ("RATIO" "CL")
      ("FFLOOR" "CL")
      ("EXPT" "CL")
      ("EXP" "CL")
      ("TAN" "CL")
      ("ISQRT" "CL")
      ("PI" "CL")
      ("COSH" "CL")
      ("ROUND" "CL")
      ("ASINH" "CL")
      ("MIN" "CL")
      ("ACOS" "CL")
      ("SIGNUM" "CL")
      ("DENOMINATOR" "CL")
      ("CIS" "CL")
      ("FCEILING" "CL")
      ("ACONS" "CL")
      ("MAX" "CL")
      ("ACOSH" "CL")
      ("COS" "CL")
      ("/" "CL")
      ("1-" "CL")
      ("-" "CL")
      ("REM" "CL")
      ("MOD" "CL")
      ("ABS" "CL")
      ("LOG" "CL")
      ))
    ("STD.CONDITIONS.TYPES" "Condition types"
     (("ERROR" "CL")
      ("SIMPLE-WARNING" "CL")
      ("STYLE-WARNING" "CL")
      ("SIMPLE-CONDITION-FORMAT-CONTROL" "CL")
      ("PROGRAM-ERROR" "CL")
      ("ARITHMETIC-ERROR-OPERANDS" "CL")
      ("FLOATING-POINT-UNDERFLOW" "CL")
      ("TYPE-ERROR-EXPECTED-TYPE" "CL")
      ("TYPE-ERROR" "CL")
      ("CONTROL-ERROR" "CL")
      ("PACKAGE-ERROR-PACKAGE" "CL")
      ("PACKAGE-ERROR" "CL")
      ("SIMPLE-ERROR" "CL")
      ("READER-ERROR" "CL")
      ("SIMPLE-TYPE-ERROR" "CL")
      ("INVALID-METHOD-ERROR" "CL")
      ("FILE-ERROR" "CL")
      ("CELL-ERROR-NAME" "CL")
      ("PARSE-ERROR" "CL")
      ("STORAGE-CONDITION" "CL")
      ("SERIOUS-CONDITION" "CL")
      ("SIMPLE-CONDITION-FORMAT-ARGUMENTS" "CL")
      ("SIMPLE-CONDITION" "CL")
      ("TYPE-ERROR-DATUM" "CL")
      ("ARITHMETIC-ERROR" "CL")
      ("ARITHMETIC-ERROR-OPERATION" "CL")
      ("CELL-ERROR" "CL")
      ("UNBOUND-VARIABLE" "CL")
      ("END-OF-FILE" "CL")
      ("FILE-ERROR-PATHNAME" "CL")
      ("UNDEFINED-FUNCTION" "CL")
      ("UNBOUND-SLOT-INSTANCE" "CL")
      ("DIVISION-BY-ZERO" "CL")
      ))
    ("STD.CONDITIONS" "Conditions"
     (("MAKE-CONDITION" "CL")
      ("DEFINE-CONDITION" "CL")
      ("INVOKE-RESTART-INTERACTIVELY" "CL")
      ("INVOKE-RESTART" "CL")
      ("RESTART-CASE" "CL")
      ("SIGNAL" "CL")
      ("USE-VALUE" "CL")
      ("HANDLER-BIND" "CL")
      ("FIND-RESTART" "CL")
      ("WARN" "CL")
      ("MUFFLE-WARNING" "CL")
      ("CERROR" "CL")
      ("COMPUTE-RESTARTS" "CL")
      ("CONDITION" "CL")
      ("CCASE" "CL")
      ("HANDLER-CASE" "CL")
      ("THROW" "CL")
      ("UNWIND-PROTECT" "CL")
      ("IGNORE-ERRORS" "CL")
      ("WITH-CONDITION-RESTARTS" "CL")
      ("ASSERT" "CL")
      ("RESTART-NAME" "CL")
      ("CATCH" "CL")
      ("CONTINUE" "CL")
      ("WITH-SIMPLE-RESTART" "CL")
      ("*BREAK-ON-SIGNALS*" "CL")
      ("STORE-VALUE" "CL")
      ("RESTART-BIND" "CL")
      ("CTYPECASE" "CL")
      ("ABORT" "CL")
      ("WARNING" "CL")
      ("RESTART" "CL")
      ))
    ("STD.CLOS" "CLOS"
     (("MAKE-INSTANCES-OBSOLETE" "CL")
      ("DEFCLASS" "CL")
      ("MAKE-INSTANCE" "CL")
      ("NO-NEXT-METHOD" "CL")
      ("*INVOKE-DEBUGGER-HOOK*" "CL")
      ("*DEBUGGER-HOOK*" "CL")
      ("CLASS-OF" "CL")
      ("TYPE-OF" "CL")
      ("SLOT-VALUE" "CL")
      ("WITH-SLOTS" "CL")
      ("WITH-ACCESSORS" "CL")
      ("FIND-CLASS" "CL")
      ("CLASS-NAME" "CL")
      ("SUBTYPEP" "CL")
      ("ADD-METHOD" "CL")
      ("DEFGENERIC" "CL")
      ("DEFMETHOD" "CL")
      ("MAKE-METHOD" "CL")
      ("CHANGE-CLASS" "CL")
      ("REINITIALIZE-INSTANCE" "CL")
      ("INITIALIZE-INSTANCE" "CL")
      ("SHARED-INITIALIZE" "CL")
      ("SLOT-UNBOUND" "CL")
      ("SLOT-MISSING" "CL")
      ("SLOT-EXISTS-P" "CL")
      ("SLOT-BOUNDP" "CL")
      ("SLOT-MAKUNBOUND" "CL")
      ("UNBOUND-SLOT" "CL")
      ("CALL-METHOD" "CL")
      ("COERCE" "CL")
      ("METHOD-COMBINATION" "CL")
      ("NEXT-METHOD-P" "CL")
      ("DEFINE-METHOD-COMBINATION" "CL")
      ("&ALLOW-OTHER-KEYS" "CL")
      ("METHOD-QUALIFIERS" "CL")
      ("REMOVE-METHOD" "CL")
      ("GENERIC-FUNCTION" "CL")
      ("CALL-NEXT-METHOD" "CL")
      ("UPDATE-INSTANCE-FOR-DIFFERENT-CLASS" "CL")
      ("FIND-METHOD" "CL")
      ("FUNCTION-KEYWORDS" "CL")
      ("NO-APPLICABLE-METHOD" "CL")
      ("ENSURE-GENERIC-FUNCTION" "CL")
      ("ALLOCATE-INSTANCE" "CL")
      ("UPDATE-INSTANCE-FOR-REDEFINED-CLASS" "CL")
      ("STANDARD-CLASS" "CL")
      ("METHOD-COMBINATION-ERROR" "CL")
      ("STANDARD-METHOD" "CL")
      ("COMPUTE-APPLICABLE-METHODS" "CL")
      ("MAKE-LOAD-FORM-SAVING-SLOTS" "CL")
      ("CLASS" "CL")
      ("BIT-VECTOR" "CL")
      ("ARRAY-ELEMENT-TYPE" "CL")
      ("STRING" "CL")
      ("SIMPLE-BIT-VECTOR" "CL")
      ("METHOD" "CL")
      ("STANDARD" "CL")
      ("STRUCTURE-OBJECT" "CL")
      ("DEFSTRUCT" "CL")
      ("STRUCTURE" "CL")
      ("COPY-STRUCTURE" "CL")
      ))
    ("STD.TYPES" "Types"
     (("COERCE" "CL")
      ("BOOLEAN" "CL")
      ("SIMPLE-STRING" "CL")
      ("CONDITION" "CL")
      ("DOUBLE-FLOAT" "CL")
      ("LONG" "CL")
      ("FLOAT" "CL")
      ("SINGLE-FLOAT" "CL")
      ("SIGNED" "CL")
      ("SEQUENCE" "CL")
      ("HASH-TABLE" "CL")
      ("BASE-CHAR" "CL")
      ("RATIONAL" "CL")
      ("REAL" "CL")
      ("CHARACTER" "CL")
      ("BYTE" "CL")
      ("NUMBER" "CL")
      ("STRUCTURE-CLASS" "CL")
      ("UNSIGNED-LONG" "CL")
      ("UNSIGNED-SHORT" "CL")
      ("STRUCT" "CL")
      ("SIMPLE-VECTOR" "CL")
      ("LONG-LONG" "CL")
      ("UNSIGNED-INT" "CL")
      ("LONG-FLOAT" "CL")
      ("ARRAY" "CL")
      ("UNSIGNED-CHAR" "CL")
      ("DOUBLE" "CL")
      ("SHORT" "CL")
      ("VOID" "CL")
      ("UNSIGNED-LONG-LONG" "CL")
      ("INT" "CL")
      ("UNSIGNED" "CL")
      ("INTEGER" "CL")
      ("STANDARD-OBJECT" "CL")
      ("SIMPLE-BASE-STRING" "CL")
      ("BUILT-IN-CLASS" "CL")
      ("UNSIGNED-BYTE" "CL")
      ("KEYWORDP" "CL")
      ("STANDARD-CHAR" "CL")
      ("BASE-STRING" "CL")
      ("STANDARD-GENERIC-FUNCTION" "CL")
      ("STANDARD-METHOD" "CL")
      ("STRUCTURE-OBJECT" "CL")
      ("STANDARD-CLASS" "CL")
      ("EXTENDED-CHAR" "CL")
      ("STANDARD-CHAR-P" "CL")
      ("LOGICAL-PATHNAME" "CL")
      ("TYPE" "CL")
      ("BIT-VECTOR-P" "CL")
      ("TYPEP" "CL")
      ("FTYPE" "CL")
      ("BIGNUM" "CL")
      )))
    "Names of each package in the hierarchy and their symbols.
Each package is a list, with:
first item: package name
second item: package description
third     : a list of:
  (symbol-name-to-export
   original-package-name)")


(defvar *clhs-chapters*
  '(("INTRODUCTION" . "")
    ("SYNTAX" . "CLHS-SYNTAX")
    ("EVALUATION AND COMPILATION" . "CLHS-EVAL")
    ("TYPES AND CLASSES" . "CLHS-TYPES")
    ("DATA AND CONTROL FLOW" . "CLHS-DATA&FLOW")
    ("ITERATION" . "CLHS-ITER")
    ("OBJECTS" . "CLHS-OBJ")
    ("STRUCTURES" . "CLHS-STRUCT")
    ("CONDITIONS" . "CLHS-COND")
    ("SYMBOLS" . "CLHS-SYMB")
    ("PACKAGES" . "CLHS-PKG")
    ("NUMBERS" . "CLHS-NUM")
    ("CHARACTERS" . "CLHS-CHAR")
    ("CONSES" . "CLHS-CONS")
    ("ARRAYS" . "CLHS-ARRAY")
    ("STRINGS" . "CLHS-STR")
    ("SEQUENCES" . "CLHS-SEQUENCE")
    ("HASH TABLES" . "CLHS-HASH")
    ("FILENAMES" . "CLHS-FILENAMES")
    ("FILES" . "CLHS-FILES")
    ("STREAMS" . "CLHS-STREAMS")
    ("PRINTER" . "CLHS-PRINTER")
    ("READER" . "CLHS-READER")
    ("SYSTEM CONSTRUCTION" . "CLHS-SYSTEM")
    ("ENVIRONMENT" . "CLHS-ENV")
    ("GLOSSARY" . "")
    )
  "Chapter names in CLHS, for a different view of syms.")


(export '(*STD-PACKAGE-DETAILS*
          *CLHS-CHAPTERS*))

